---
###############################################################################
#                                                                             #
#                            WEBSITE CONFIGURATION                            #
#                                                                             #
###############################################################################


# --- base website settings ---

title: Miqesi
baseURL: https://miqesi.org/
theme: toph
locale: en-us
enableEmoji: true
enableGitInfo: true
enableRobotsTXT: false
#googleAnalytics: TBD


# --- taxonomy and pagination settings ---

taxonomies:
  tag: tags
  category: categories
pagination:
  pagerSize: 10


# --- security settings ---

security:
  exec:
    allow: ['^dart-sass-embedded$', '^git$', '^go$', '^npx$', '^postcss$', '^asciidoctor$']


# --- markup settings ---

markup:
  asciidocExt:
    preserveTOC: true
  highlight:
    style: github


# --- privacy settings ---

privacy:
  googleAnalytics:
    anonymizeIP: true
    respectDoNotTrack: true
  x:
    enableDNT: true
  youtube:
    privacyEnhanced: true


# --- navigation menu ---

menu:
  nav:
    - identifier: home
      name: home
      url: /
      weight: 10
    - identifier: blog
      name: blog
      url: /blog/
      weight: 20
    - identifier: categories
      name: categories
      url: /categories/
      parent: blog
      weight: 30
    - identifier: tags
      name: tags
      url: /tags/
      parent: blog
      weight: 40


# --- custom settings ---

params:
  biography:
    name: Miqesi
    tagline: ""
    email: ""
    blog: ""
    first_online: 2024
    knows_about: [
      "a11y",
      "accessibility",
      "diversity",
      "equity",
      "Fedora Project",
      "Free Software",
      "inclusion",
      "Linux",
      "open source",
      "Red Hat",
      "Red Hat Enterprise Linux (RHEL)",
      "RPM package management",
      "user experience"
    ]
  colors:
    primary: "#AD1457"
    secondary: "#F8F6F0"
    accent: "#33691E"
  description: Home of Project Miqesi.
  fonts:
    default: Atkinson Hyperlegible Next
    default_weight: ":wght@400;700"
    title: Inter
    title_weight: ":wght@900"
    header: Inter
    header_weight: ":wght@700"
  images:
    - /img/logo.png
  favicon: /favicon.ico
  git_repo: https://github.com/miqesi/miqesi.org
  taxonomy_exclude: ["footer", "projects"]
  hire_me: false
  social:
    # github: ""
    # gitlab: ""
    # linkedin: ""
    # mastodon: ""
  legal:
    license:
      name: ""
      url: ""
      title: ""
  date_format: "2006 January 02"
  layouts:
    categories:
      recent_posts: 3
      excerpt_length: 250


# --- internationalization settings ---

defaultContentLang: en
languages:
  en:
    label: English
